[Semana 8] Testes
NickMendes/ecomm pull request #12
Opened 2023-03-02 12:57 UTC by NickMendes

2023-03-07 14:49 UTC, DPechetti requested changes

2023-03-07 14:49 UTC, DPechetti commented on account/src/test/routes/UserRoute.test.js
> +            .expect(500);
is this really supposed to be 500?

2023-03-07 14:49 UTC, DPechetti commented on account/src/test/routes/UserRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on finance-mongo/src/test/routes/CupomRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on finance-mongo/src/test/routes/CupomRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on finance-mongo/src/test/routes/PaymentRoute.test.js
> +            .expect(500);
is this really supposed to be 500?

2023-03-07 14:49 UTC, DPechetti commented on finance-mongo/src/test/routes/PaymentRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on finance-mongo/src/test/routes/PaymentRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on account/src/test/routes/UserRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on finance/api/tests/PaymentRoute.test.js
> +            .expect(500);
is this really supposed to be 500?

2023-03-07 14:49 UTC, DPechetti commented on finance/api/tests/PaymentRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on order/src/test/routes/SalesRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on order/src/test/routes/SalesRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on package.json
> +    "jest": "^29.4.3"
do you need the jest here?

2023-03-07 14:49 UTC, DPechetti commented on product/src/tests/routes/categoryRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on product/src/tests/routes/categoryRoute.test.js
> +            .expect(500);
is this really supposed to be 500?

2023-03-07 14:49 UTC, DPechetti commented on product/src/tests/routes/categoryRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on product/src/tests/routes/categoryRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on product/src/tests/routes/productRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-07 14:49 UTC, DPechetti commented on product/src/tests/routes/productRoute.test.js
> +            .expect(202);
is this really supposed to be 202?

2023-03-08 19:07 UTC, merged

2023-03-11 00:01 UTC, tiagolpadua commented on account/package.json
> +    "test": "node --experimental-vm-modules node_modules/jest/bin/jest.js --verbose",
Seria interessante ter um script específico para o eslint, para facilitar sua execução, algo como:
"lint": "eslint src"

2023-03-11 00:03 UTC, tiagolpadua commented on account/src/controllers/UserController.js
> +                res.status(400).send({ message: err.message });
Erros na faixa do 400 em geral indicam algum erro nos dados enviados na requisição, neste caso, seria mais adequado um erro na faixa do 500

2023-03-11 00:03 UTC, tiagolpadua commented on account/src/controllers/UserController.js
> +                res.status(200).json(user);
Seria bom tratar o caso de entidade não encontrada retornando 404

2023-03-11 00:03 UTC, tiagolpadua commented on account/src/controllers/UserController.js
> +        let user = new users(req.body);
Prefira utilizar nomes de classes e modelos no singular e com a primeira letra em maiúsculo, como no exemplo do mongoose: https://mongoosejs.com/docs/models.html#compiling

2023-03-11 00:09 UTC, tiagolpadua commented
Card1 - Testando os endpoints da API de produtos	Ok
Card2 - Testando os endpoints da API de pagamentos	Ok
Card3 - Configuração do ES Lint	Ok
Card4 - Testando os endpoints da API de usuários	Ok
Card5 - Testando os endpoints da API de pedidos	Ok